from __future__ import annotations

from typing import Protocol, runtime_checkable

from .storage import SQLiteStore


@runtime_checkable
class Store(Protocol):
    def list_projects(self): ...
    def get_project(self, project_id: str): ...
    def save_project(self, project): ...
    def list_document_chunks(self, project_id: str, limit: int = 8): ...
    def get_uploaded_paper(self, project_id: str, paper_id: str): ...
    def save_agent_run(self, project_id: str, run): ...
    def get_quality_report(self, project_id: str, report_id: str): ...
    def save_tenant_bundle(self, user, team, membership, subscription): ...
    def get_user_by_email(self, email: str): ...
    def get_user(self, user_id: str): ...
    def get_team(self, team_id: str): ...
    def list_team_memberships(self, user_id: str | None = None, team_id: str | None = None): ...
    def record_usage_event(self, event): ...
    def list_usage_events(self, subject_id: str | None = None): ...
    def list_subscriptions(self, team_id: str | None = None): ...
    def save_job(self, job): ...
    def get_job(self, job_id: str): ...
    def list_jobs(self, project_id: str | None = None): ...
    def save_object_record(self, record): ...
    def get_object_record(self, object_id: str): ...
    def list_object_records(self, project_id: str | None = None): ...


def build_store() -> Store:
    from .config import settings

    if settings.resolved_store_backend == "postgres":
        from .postgres_store import PostgresStore

        return PostgresStore(settings.database_url)
    return SQLiteStore(settings.db_path)
